name: Nightly Integration Tests

on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    # Remove if you don't need a database
    services:
      db:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: phoenix_react_template_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: 1.16.2
          otp-version: 26.2.4

      - name: Run Migrations
        run: mix ecto.migrate
        if: always()

      - name: Run Tests
        run: mix test --include integration
